### ISSUE TITLE
Please edit the topic to Hacktoberfest

### ISSUE THREAD

**Issue by PriyavKaneria** [atyant-yadav/Hacktoberfest2020#267]
Currently, it is marked as not participating in hac**k**toberfest because the topic currently does not have the 'k' of Hac**k**tober.
Please do it as soon as possible so the PR's get counted.
And also mark hac**k**toberfest-accepted with the k in it.
Thanks in advance

**Comment by umangag07** [comment]
Yes, can you add topics "hactoberfest", "hactoberfest-2020" in the topic otherwise this repo won't be particpating.

**Comment by atyant-yadav** [comment]
@PriyavKaneria @umangag07 
Thanks for the info!

I have made the required changes. Feel free to dm me if there's some issue. :)
