### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Th3-N3rd** [atyant-yadav/Hacktoberfest2020#564]
Hey there,
Add CONTRIBUTING.md to ensure that what are things that are to be included while contributing.

Happy Hactoberfest...!!!!

**Comment by yugrajani** [comment]
Hello, I'd like to claim this issue. Will you assign it to me, please?

**Comment by Th3-N3rd** [comment]
Hey there,
Sure you can do. But ask the repository maintainer if possible.
Regards
Th3-N3rd.

**Comment by yugrajani** [comment]
Thank you @Th3-N3rd.
Hey @atyant-yadav, may I?

**Comment by atyant-yadav** [comment]
Sure @Th3-N3rd and @yugrajani 
Go ahead and add CONTRIBUTING.md and comment down the PR link here.
I will review and do the needful. ^_^

**Comment by yugrajani** [comment]
Okay thank you, will try to complete the same at the earliest possible.

**Comment by yugrajani** [comment]
> Sure @Th3-N3rd and @yugrajani
> Go ahead and add CONTRIBUTING.md and comment down the PR link here.
> I will review and do the needful. ^_^

@atyant-yadav PR Link:
[](https://github.com/atyant-yadav/Hacktoberfest2020/pull/659) 
#659 

Thanks for providing the opportunity @atyant-yadav @Th3-N3rd.

**Comment by atyant-yadav** [comment]
@yugrajani good job 👍
