### ISSUE TITLE
stack

### ISSUE THREAD

**Issue by PriyaGandhi311** [atyant-yadav/Hacktoberfest2020#936]
hey @atyant-yadav if i add a code for stack in cpp files will it count for hacktoberfest2020?
if yes then i would like to make a pr.

**Comment by atyant-yadav** [comment]
Yes, any PR will count for hacktoberfest. 
Go ahead @PriyaGandhi311 .

**Comment by PriyaGandhi311** [comment]
@atyant-yadav i made a PR but it is shows not eligible repo status on hacktober fest profile, pls help.

**Comment by atyant-yadav** [comment]
Can you provide me the link to that PR.

**Comment by PriyaGandhi311** [comment]
https://github.com/PriyaGandhi311/Hacktoberfest2020/pull/1

**Comment by atyant-yadav** [comment]
@PriyaGandhi311 make a pull request to my repo.

**Comment by PriyaGandhi311** [comment]
can u pls help me with that, since this is my first time to open source?

**Comment by atyant-yadav** [comment]
@PriyaGandhi311 the link which u provided earlier, u made that PR in your forked repo.

so open my repo
make new pull request in my repo.

**Comment by PriyaGandhi311** [comment]
@atyant-yadav I made a pr in ur repo as u said, can you pls review it?

**Comment by atyant-yadav** [comment]
@PriyaGandhi311 good job. :)

**Comment by PriyaGandhi311** [comment]
Thankyou so much! 💯
